### ISSUE TITLE
Error message when language content page does not exist

### ISSUE THREAD

**Issue by andreasba** [tobiasfabian/kirby-machine-translation#3]
When I create a new page (default: EN), then I switch to DE and open the Machine Translation tab in the panel, I get the following error:

![image](https://github.com/tobiasfabian/kirby-machine-translation/assets/15323226/d6861604-e4ed-4b48-8cc4-104034b9459c)

I am running Kirby 4 Beta 1 - is this me or the plugin?

**Comment by tobiasfabian** [comment]
It’s actually Beta 1. But it’s already fixed with https://github.com/getkirby/kirby/commit/c90057c9aeeb4b7be5c84fa4cc2207648a792143
