### ISSUE TITLE
Page references are translated resulting in broken links/references

### ISSUE THREAD

**Issue by andreasba** [tobiasfabian/kirby-machine-translation#4]
Kirby offers the option to select related pages and store them in the content file: https://getkirby.com/docs/reference/panel/fields/pages

The machine translation should ignore this field because when translated, the relation is broken and does not work anymore.

**Comment by tobiasfabian** [comment]
I haven't been able to reproduce this issue. `pages` fields aren't being translated. See [field-methods/translate.php#L35-L55](https://github.com/tobiasfabian/kirby-machine-translation/blob/main/field-methods/translate.php#L35-L55)

Are the _related pages_ inside another file (like `object`, `blocks`, `structure`, etc.)?

To prevent content from being translated (regardless of machine translation), you can add `translate: false` to any field.

**Comment by andreasba** [comment]
It is a select field type:

`        fields:
          category:
            label: The category of the question
            type: select
            options:
              "About the Company":
                en: About Companyname
                de: Über Firmenname
              "Commercials":
                en: Commercials
                de: Kommerzielles
              "Accounting":
                en: Accounting and Invoicing
                de: Buchhaltung und Rechnung
`

Sorry for being not specific enough :)

**Comment by tobiasfabian** [comment]
Select fields aren’t translated either.
The cause of the problem must lie elsewhere.
